import { jsPDF } from 'jspdf';

export function exportDreamRecapPDF(user: { username: string }, summary: { totalDreams: number; lastMonthCount: number }, topSymbols: Array<{ keyword: string; count: number; theme: string }>, moods: Array<{ name: string; count: number }>) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });
  
  // 1. Premium Header (Dark Indigo Banner)
  doc.setFillColor(9, 9, 14); // Very dark navy
  doc.rect(0, 0, 210, 45, 'F');
  
  // Header text
  doc.setTextColor(192, 132, 252); // Soft purple accent
  doc.setFont('Helvetica', 'Bold');
  doc.setFontSize(26);
  doc.text("DREAMOLA", 15, 20);
  
  doc.setTextColor(255, 255, 255);
  doc.setFont('Helvetica', 'Normal');
  doc.setFontSize(10);
  doc.text("YOUR PERSONAL SUB-CONSCIOUS METRICS RECAP", 15, 30);
  
  // 2. Report Metadata Card
  doc.setTextColor(30, 30, 40);
  doc.setFont('Helvetica', 'Bold');
  doc.setFontSize(16);
  doc.text(`Dream Journal Insights — u/${user.username}`, 15, 60);
  
  doc.setFont('Helvetica', 'Normal');
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 110);
  doc.text(`Generated On: ${new Date().toLocaleDateString()}`, 15, 68);
  doc.text(`Total Dream Records Logged: ${summary.totalDreams}`, 15, 74);
  doc.text(`Active Records (Last 30 Days): ${summary.lastMonthCount}`, 15, 80);
  
  // Horizontal Rule
  doc.setDrawColor(220, 220, 230);
  doc.line(15, 86, 195, 86);
  
  // 3. Top Recurring Symbols section
  doc.setTextColor(147, 51, 234); // Purple
  doc.setFont('Helvetica', 'Bold');
  doc.setFontSize(14);
  doc.text("Top Recurring Dream Symbols", 15, 96);
  
  let y = 106;
  doc.setTextColor(50, 50, 60);
  
  if (topSymbols.length === 0) {
    doc.setFont('Helvetica', 'Oblique');
    doc.setFontSize(10);
    doc.text("No symbols identified yet. Log more dreams to see recurring themes.", 15, y);
    y += 12;
  } else {
    topSymbols.forEach((sym, idx) => {
      // Bold Symbol header
      doc.setFont('Helvetica', 'Bold');
      doc.setFontSize(10);
      doc.text(`${idx + 1}. '${sym.keyword}' (Appeared ${sym.count}x)`, 15, y);
      
      // Muted description paragraph
      doc.setFont('Helvetica', 'Normal');
      doc.setFontSize(9);
      doc.setTextColor(100, 100, 110);
      
      const themeText = sym.theme.length > 80 ? `${sym.theme.slice(0, 80)}...` : sym.theme;
      doc.text(`Meaning: ${themeText}`, 20, y + 5);
      doc.setTextColor(50, 50, 60); // reset
      
      y += 15;
    });
  }
  
  // Divider
  doc.line(15, y + 2, 195, y + 2);
  
  // 4. Mood breakdown section
  doc.setTextColor(99, 102, 241); // Indigo
  doc.setFont('Helvetica', 'Bold');
  doc.setFontSize(14);
  doc.text("Mood Frequency Analysis", 15, y + 12);
  
  let moodY = y + 22;
  doc.setFont('Helvetica', 'Normal');
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 60);
  
  if (moods.length === 0) {
    doc.setFont('Helvetica', 'Oblique');
    doc.text("No mood tags selected in your dream entries.", 15, moodY);
  } else {
    moods.forEach((m) => {
      doc.setFont('Helvetica', 'Bold');
      doc.text(`${m.name.charAt(0).toUpperCase() + m.name.slice(1)}:`, 15, moodY);
      doc.setFont('Helvetica', 'Normal');
      doc.text(`${m.count} dream records`, 45, moodY);
      moodY += 7;
    });
  }
  
  // 5. Branded Footer
  doc.setFont('Helvetica', 'Oblique');
  doc.setFontSize(8);
  doc.setTextColor(160, 160, 170);
  doc.text("Report generated by Dreamola AI Journal. Not psychological or medical advice.", 15, 280);
  
  doc.save(`Dreamola_Recap_${user.username}.pdf`);
}
