export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#09090e] text-white p-4 md:p-8 flex justify-center">
      <div className="w-full max-w-3xl pb-32 mt-12 space-y-6 font-serif leading-relaxed">
        <h1 className="text-4xl md:text-5xl text-purple-200 mb-8">Terms & Conditions</h1>
        
        <p className="text-sm text-white/40">Last Updated: August 16, 2026</p>

        <p className="text-lg text-white/80">
          Welcome to Dreamola. By accessing or using our website, AI dream interpretation services, and payment integrations, you agree to comply with and be bound by the following Terms and Conditions.
        </p>

        <h2 className="text-2xl text-purple-200/90 mt-8">1. Acceptable Use of Services</h2>
        <p className="text-lg text-white/80">
          Dreamola provides personal, self-reflective tools for interpreting dream content and generating digital dream illustrations. You agree not to submit explicit, illegal, or harmful narratives to our content processing engines.
        </p>

        <h2 className="text-2xl text-purple-200/90 mt-8">2. Account Registration</h2>
        <p className="text-lg text-white/80">
          You must provide accurate information when registering for an account. You are responsible for keeping your login credentials secure and confidential. Dreamola is not liable for unauthorized access resulting from your failure to protect your credentials.
        </p>

        <h2 className="text-2xl text-purple-200/90 mt-8">3. Subscriptions & Payments</h2>
        <p className="text-lg text-white/80">
          Paid plans (Lucid and Oracle tiers) grant you expanded daily usage limits, dream journal storage, and PDF summary exports. Subscription payments are processed via Razorpay secure checkouts. By upgrading, you authorize monthly billing at the specified plan price.
        </p>

        <h2 className="text-2xl text-purple-200/90 mt-8">4. Intellectual Property</h2>
        <p className="text-lg text-white/80">
          You retain full ownership of the dream descriptions and written contents you log in your private journal. Digital illustrations generated by the platform are subject to open-use or shared public terms if posted to our public community gallery.
        </p>

        <h2 className="text-2xl text-purple-200/90 mt-8">5. Disclaimers & Limitations</h2>
        <p className="text-lg text-white/80">
          All dream interpretations provided by Dreamola are generated automatically by artificial intelligence models. These reflections are meant solely as creative and self-reflective tools. They do not constitute professional, medical, psychiatric, or legal advice.
        </p>

        <h2 className="text-2xl text-purple-200/90 mt-8">6. Contact Us</h2>
        <p className="text-lg text-white/80">
          If you have any questions or require support regarding these terms, please contact us at <span className="underline text-purple-300">anshudayma23@gmail.com</span>.
        </p>
      </div>
    </div>
  );
}
